### ISSUE TITLE
Support CCXT

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/vigilant-crypto-snatch#27]
There is the [CCXT](https://docs.ccxt.com/en/latest/index.html) library which abstracts various marketplaces. Integrating this would give us access to many more exchanges, potentially making it more relevant for more users.

Tasks:

- [x] Check that the license is compatible with ours (MIT)
- [x] See whether it supports the basic features that we need, although that is likely the case.
- [x] Implement another marketplace with that.

**Comment by MartinKei** [comment]
@martin-ueding 
CCXTs license is MIT
https://github.com/ccxt/ccxt/blob/master/LICENSE.txt
