### ISSUE TITLE
the get_value method in the AlternateMeFearAndGreedIndex Class crashes sometimes (throws exception)

### ISSUE THREAD

**Issue by ziggie1984** [martin-ueding/vigilant-crypto-snatch#32]
Version Tested: 5.4.2

When using the Fear and Greed Index Trigger, the cmd command "watch" crashes when the date of the FaG Api (https://api.alternative.me/fng/) returns the date of the day before although the current date is one day later. 

_File: vigilant_crypto_snatch/feargreed/alternateme.py_
 return cached_values[now] operation will try to access a key-value pair, which has no valid key and the program throws an unhandled exception.

In addition there is still a print() statement in the file, which prints the caches values "cached_values" into the console. Would be better to either log this message with a description prefix or omit it entirely.

Error Code:
🔴 Unhandled exception type: KeyError(datetime.date(2022, 1, 21)). Please report this to Martin!

**Comment by martin-ueding** [comment]
That should be fixed in the next version. If now, reopen.
